version: "3.7"
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - flask_todo_app:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
        - "3306:3306"

volumes:
    flask_todo_app: