version: "3.7"
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - flask_todo_app:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
        - "3306:3306"
  todo-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
    flask_todo_app: